services:
  caddy:
    image: caddy
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./private:/etc/caddy/private
      - ./data:/data
      - ./config:/config

    networks:
      - proxy

networks:
  proxy:
    external: true
