services:
  db:
    image: postgres:14
    container_name: nextcloud-db
    restart: always
    networks:
      - nextcloud
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud-db
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  
  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: always
    networks:
      - nextcloud
    command: redis-server --requirepass ${REDIS_PASSWORD}

  app:
    image: nextcloud
    container_name: nextcloud
    restart: always
    networks:
      - nextcloud
      - proxy
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_DB: nextcloud-db
      - POSTGRES_USER: ${DB_USER}
      - POSTGRES_PASSWORD: ${DB_PASSWORD}
      - POSTGRES_HOST: db
      - REDIS_HOST: redis
      - REDIS_HOST_PASSWORD: ${REDIS_PASSWORD}
      - NEXTCLOUD_ADMIN_USER: ${ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS: cloud.node804
    depends_on:
      - db
      - redis

volumes:
  nextcloud:
  db:

networks:
  nextcloud:
    external: false
  proxy:
    external: true
